### PR TITLE
ENTESB-13287 adding a soap source crd example

### PR DESCRIPTION
**Pull request by shawkins**

### CODE REVIEW

**Comment by shawkins** [comment]
using the env properties for now as the new style properties seem to have issues.

**Comment by rareddy** [comment]
What issues other than it forces you to define in lowercase data source names?

**Comment by shawkins** [comment]
See the additional comments on https://issues.redhat.com/browse/TEIIDTOOLS-975

**Comment by rareddy** [comment]
@shawkins can we add this example to the Operator CRs, instead of here. There is a pattern emerging on Operator installs in 4.4 where these can be exposed as examples directly on Operator.

**Pull request closed without merging**
